# примеры API-запросов

@baseUrl = http://localhost:8000/api

# получение объявлений
GET {{baseUrl}}/adv/
Content-Type: application/json

###

# создание объявления
POST {{baseUrl}}/adv/
Content-Type: application/json
Authorization: Token 5252419dcc9fdf699ef54db95c4292a40b7391a5

{
  "title": "Шкаф IKEA",
  "description": "Срочно"
}

###

# попытка поменять объявление
PATCH {{baseUrl}}/adv/1/
Content-Type: application/json
Authorization: Token 5252419dcc9fdf699ef54db95c4292a40b7391a5

{
  "status": "CLOSED"
}

###

# фильтрация по создателю
GET {{baseUrl}}/adv/?creator=3
Content-Type: application/json

###

# фильтрация по дате
GET {{baseUrl}}/adv/?created_at_before=2020-10-01
Content-Type: application/json
