# Generated by Django 4.1.7 on 2023-03-13 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_articletheme_theme_articletheme_theme'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='theme',
            name='article',
        ),
        migrations.AlterField(
            model_name='articletheme',
            name='is_main',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='theme',
            name='theme',
            field=models.CharField(max_length=50, unique=True, verbose_name='Название'),
        ),
    ]
